name = "Default Modpack 1.19.2 Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dd0ffd441e18d3b5630b0a134a91004a453c9db05bee33c95def1fae0d0dc3e"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
