name = "Default Modpack 1.19.2 Fabric"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b47c413ceb2b21cc41eed3cfe0a283f5cab723d9758a2ba83a6cfb871ce4c1a"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
